Update requirements
Islandora-Devops/isle-dc pull request #187
Opened 2021-10-14 18:06 UTC by DonRichards

Added a link to a ticket that includes more information on getting composer to work correctly.
Removed drush because these requirements are for the local machine and not for what's in the container.

2021-10-17 13:42 UTC, nigelgbanks requested changes

2021-10-17 13:42 UTC, nigelgbanks commented on README.md
> +- Composer 1.10+ (see [issues/184](https://github.com/Islandora-Devops/isle-dc/issues/184) for help). 2.x currently does not work.
The comment here is about `docker-compose` not PHP's `composer` tool.

2021-10-17 13:42 UTC, nigelgbanks commented on README.md
> -- Drush 9.0+
Good catch.

2021-10-20 13:26 UTC, DonRichards commented on README.md
> +- Composer 1.10+ (see [issues/184](https://github.com/Islandora-Devops/isle-dc/issues/184) for help). 2.x currently does not work.
:facepalm: Noted, I'll make that adjustment.

2021-10-20 13:31 UTC, DonRichards commented on README.md
> +- Composer 1.10+ (see [issues/184](https://github.com/Islandora-Devops/isle-dc/issues/184) for help). 2.x currently does not work.
@nigelgbanks OK, got it.

2021-10-27 15:25 UTC, DonRichards commented
@nigelgbanks Good to merge?

2021-10-27 16:06 UTC, jordandukart commented
Just an FYI @DonRichards this is merge conflicting.

2021-10-27 21:12 UTC, merged

2021-10-27 21:13 UTC, nigelgbanks commented
Good stuff