fix for public file export path
Islandora-Devops/isle-dc pull request #338
Opened 2023-05-18 18:07 UTC by joshdentremont

When exporting the public files directory the tar was being created with the path /var/www/drupal/web/sites/default/files, and then when that dump was imported, it would be placed back at that location and duplicate the path. This meant files are being placed at /var/www/drupal/web/sites/default/files/var/www/drupal/web/sites/default/files.

This PR changes the path inside the exported dump to be ./ which will allow us to extract the files wherever we want.

To reproduce the issue:
- Install a fresh starter site with `make starter`
- check the files directory with `docker-compose exec drupal with-contenv bash -lc 'ls /var/www/drupal/web/sites/default/files'`
- `make drupal-public-files-dump DEST=files.tgz`
- `make drupal-public-files-import SRC=files.tgz`
- `docker-compose exec drupal with-contenv bash -lc 'ls /var/www/drupal/web/sites/default/files'` again
You should see that you now have your files duplicated at /var/www/drupal/web/sites/default/files/var/www/drupal/web/sites/default/files

To test this PR works:
- add something to the files directory with `docker-compose exec drupal with-contenv bash -lc 'touch /var/www/drupal/web/sites/default/files/test.txt'`
- `docker-compose exec drupal with-contenv bash -lc 'ls /var/www/drupal/web/sites/default/files'`
- `make drupal-public-files-dump DEST=files.tgz`
- remove the file with `docker-compose exec drupal with-contenv bash -lc 'rm /var/www/drupal/web/sites/default/files/test.txt'`
- `docker-compose exec drupal with-contenv bash -lc 'ls /var/www/drupal/web/sites/default/files'`
- `make drupal-public-files-import SRC=files.tgz`
- `docker-compose exec drupal with-contenv bash -lc 'ls /var/www/drupal/web/sites/default/files'`
You should see that your file was added back to the correct location from the import

2023-05-24 18:13 UTC, rosiel commented
During committers call, decided we can fix this but need an option to use the old behaviour, in case people have workflows set up that rely on it working as it does now.

2023-05-24 19:11 UTC, joshdentremont commented
This should now let you specify the path. For the old behaviour, set the variable in your .env to `PUBLIC_FILES_TAR_DUMP_PATH=/var/www/drupal/web/sites/default/files`

2023-07-19 16:55 UTC, aOelschlager commented
Finally got to testing this, sorry for the delay. I followed the testing pr instructions and it works.

2023-07-19 16:56 UTC, aOelschlager requested changes
Finally got to testing this, sorry for the delay. I followed the testing pr instructions and it works. It's a few commits behind main but otherwise good to merge.

2023-07-20 15:13 UTC, aOelschlager approved these changes
Ready to merge now. Thanks Josh!

2023-08-02 17:43 UTC, merged