Fix for the issue https://github.com/Islandora-Devops/isle-dc/issues/372
Islandora-Devops/isle-dc pull request #407
Opened 2024-09-12 02:42 UTC by kylehuynh205

# About 
This PR is the fix for enabling [Code Server in isle-dc](https://github.com/Islandora-Devops/isle-dc?tab=readme-ov-file#code-server). There is also existing issue https://github.com/Islandora-Devops/isle-dc/issues/372

The error: 

````
make up
[+] Running 19/19
 ✔ Network isle-dc_default          Created                                                                                0.0s 
 ✔ Network isle-dc_gateway          Created                                                                                0.0s 
 ✔ Volume "isle-dc_drupal-root"     Created                                                                                0.0s 
 ✔ Container isle-dc-hypercube-1    Started                                                                                0.8s 
 ✔ Container isle-dc-solr-1         Started                                                                                1.1s 
 ✔ Container isle-dc-activemq-1     Started                                                                                1.7s 
 ✔ Container isle-dc-blazegraph-1   Started                                                                                1.1s 
 ✔ Container isle-dc-homarus-1      Started                                                                                1.3s 
 ✔ Container isle-dc-fits-1         Started                                                                                1.0s 
 ✔ Container isle-dc-alpaca-1       Started                                                                                1.4s 
 ✔ Container isle-dc-cantaloupe-1   Started                                                                                1.4s 
 ✔ Container isle-dc-mariadb-1      Started                                                                                1.0s 
 ✔ Container isle-dc-houdini-1      Started                                                                                1.6s 
 ✔ Container isle-dc-milliner-1     Started                                                                                1.3s 
 ✔ Container traefik                Started                                                                                1.6s 
 ✔ Container isle-dc-drupal-1       Started                                                                                2.5s 
 ✔ Container isle-dc-crayfits-1     Started                                                                                1.7s 
 ✔ Container isle-dc-fcrepo-1       Started                                                                                2.3s 
 ✔ Container isle-dc-code-server-1  Started                                                                                2.7s 

 Sleeping for 10 seconds to wait for Drupal to finish building.

Could not open input file: /var/www/drupal/vendor/bin/drush
realpath: /sites/default: No such file or directory
/etc/islandora/utilities.sh: line 352: site_directory: parameter null or not set
grep: /var/www/drupal/web/sites/default/settings.php: No such file or directory
Could not open input file: /var/www/drupal/vendor/bin/drush
Could not open input file: /var/www/drupal/vendor/bin/drush
Could not open input file: /var/www/drupal/vendor/bin/drush
Could not open input file: /var/www/drupal/vendor/bin/drush
Could not open input file: /var/www/drupal/vendor/bin/drush
Could not open input file: /var/www/drupal/vendor/bin/drush
Could not open input file: /var/www/drupal/vendor/bin/drush
realpath: /sites/default: No such file or directory
/etc/islandora/utilities.sh: line 380: site_directory: parameter null or not set
make: *** [up] Error 127

````

From the suggestion form [HyphenHook](https://github.com/HyphenHook) in https://github.com/Islandora-Devops/isle-dc/issues/372#issuecomment-1939084089. the code server can be enabled successfully. This PR brings in the fix for that.

2024-09-18 18:56 UTC, aOelschlager requested changes

2024-09-18 18:56 UTC, aOelschlager commented on build/docker-compose/docker-compose.code-server.yml
> +version: '3.7'
We don't need to use version numbers anymore and they were removed from the rest of the docker compose files with this [pr](https://github.com/Islandora-Devops/isle-dc/pull/404)

I can test this after that change is made, but everything looks good. Thanks Kyle!

2024-10-03 13:58 UTC, kylehuynh205 commented on build/docker-compose/docker-compose.code-server.yml
> +version: '3.7'
I have removed the version in the yml file in the latest [commit](https://github.com/Islandora-Devops/isle-dc/pull/407/commits/ba1c4f611d6dfaf86d230806e5ec9f05938c2e2c) in the branch

2025-05-28 17:31 UTC, closed without merging

2025-05-28 17:31 UTC, seth-shaw-asu commented
Out of date. Code server is no longer being supported.