Bring isle-dc in line with isle-buildkit
Islandora-Devops/isle-dc pull request #81
Opened 2020-06-04 15:36 UTC by noahwsmith

There are three levels required:

1. Allow local dev
2. Allow spin up of new site from islandora starter
3. Facilitate building remote deploy image

This PR should probably be accepted after we can achieve #1.

2020-06-04 15:37 UTC, noahwsmith commented
From @birkland 

> One thing to note is that for isle-dc, we'd eventually want to move away from the paradigm where each service has its own domain name (introduced in isle-buildkit). e.g instead of cantaloupe.localhost, drupal.localhost, fcrepo.localhost, use something akin to isle.localhost/fcrepo, isle.localhost/iiif, etc. Path-based routing instead of host-based. It's fine to use a host-based approach in isle-buildkit, but it's not a pattern folks will use in real life when they deploy an ISLE stack for staging/test/production

2020-06-17 02:44 UTC, noahwsmith commented
@dannylamb @g7morris @nigelgbanks @nikathone @bseeger 

Ok, I'm ready to bring this back in. See the docs files under docs/recipes -- the DEMO one works flawlessly as a "boot up Nigel's sandbox" process. The LOCAL one works great for the "bring your own app" variant (because you load your own db which gets around the issue below) but I'm having issues with the "initialize a new app from scratch" which may require changing the "03" script from the Drupal image - it tries to do a site install, and quits because of permissions issues. If it failed silently and stayed up then we could work with it, but s6 just reboots the system infinitely waiting for a database, which we can't install without being able to run drush on the drupal container.

Thoughts?

2020-06-17 14:35 UTC, nigelgbanks reviewed
I spun up the demo locally following the instructions: <https://github.com/noahwsmith/isle-dc/blob/combine-nigel-nia/docs/recipes/DEMO.md>, and got the following error:
```
The website encountered an unexpected error. Please try again later.
```

Seems to be `fedora` is the culprit error appear on <http://islandora.localhost/node/1> after adding a repo item. 

Turns out it was using an older image for sandbox. I needed to pull it as well. I'll put a comment in the relevant spot.

2020-06-17 14:49 UTC, nigelgbanks commented on docs/recipes/DEMO.md
> +  * `docker-compose pull`
To ensure their isn't a mismatch between the images we need to pull for all of the `docker-compose.yml` files that will be used.

```
docker-compose -f docker-compose.yml -f docker-compose.demo.yml pull
```

2020-06-17 14:56 UTC, nigelgbanks commented on docs/recipes/DEMO.md
> +  * `docker-compose pull`
Actually seems the make file can do this already:

``
make pull
``

Would be a better fit.

2020-06-17 15:11 UTC, noahwsmith commented on docs/recipes/DEMO.md
> +  * `docker-compose pull`
Yes, that's correct. Not sure if it solves your issue, though? Could you post a gist of your full trace with the error?

2020-06-17 15:13 UTC, nigelgbanks commented
In following the local instructions here: <https://github.com/noahwsmith/isle-dc/blob/combine-nigel-nia/docs/recipes/LOCAL.md>

I got the following errors for generating the keys when running ``make install_islandora``:

```bash
Generating RSA Keys
chmod: /opt/keys/claw: No such file or directory
genrsa: Can't open "/opt/keys/claw/private.key" for writing, No such file or directory
Can't open /opt/keys/claw/private.key for reading, No such file or directory
140443857227080:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/opt/keys/claw/private.key','r')
140443857227080:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load Private Key
```

The install continued after that point.

Got an error about chmod being called with the incorrect parameters:

```bash
**BusyBox v1.31.1 () multi-call binary.

Usage: chmod [-Rcvf] MODE[,MODE]... FILE...

Each MODE is one or more of the letters ugoa, one of the
symbols +-= and one or more of the letters rwxst

        -R      Recurse
        -c      List changed files
        -v      List all files
        -f      Hide errors
```

Followed by more JWT errors.

```bash
 1/16 [=>--------------------------]   6% [error]  Error getting JWT token for message. Check JWT Configuration. 
 [error]  Error getting JWT token for message. Check JWT Configuration. 
```

As well as some issue with solr which is probably unrelated to the JWT stuff.

```bash
 [error]  Drupal\search_api_solr\SearchApiSolrException while indexing: Solr endpoint http://solr:8983/ not found (404). <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/ISLANDORA/update. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
 in Drupal\search_api_solr\SolrConnector\SolrConnectorPluginBase->handleHttpException() (line 894 of /var/www/drupal/web/modules/contrib/search_api_solr/src/SolrConnector/SolrConnectorPluginBase.php). 
 [error]  Drupal\search_api_solr\SearchApiSolrException while trying to index items on Default Solr content index: Solr endpoint http://solr:8983/ not found (404). <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/ISLANDORA/update. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
 in Drupal\search_api_solr\Plugin\search_api\backend\SearchApiSolrBackend->indexItems() (line 998 of /var/www/drupal/web/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php). 
```
The script still returned successful after executing though.

2020-06-17 15:15 UTC, nigelgbanks commented on docs/recipes/DEMO.md
> +  * `docker-compose pull`
Oh it solved the issue for me, as I had an older sandbox pre Danny's changes to JWT generation.

2020-06-17 15:22 UTC, nigelgbanks commented on config/drupal/key.key.islandora_rsa_key.yml
> +  file_location: /opt/keys/claw/private.key
Path has changed since https://github.com/Islandora-Devops/isle-buildkit/pull/47

Should now be: ``/opt/keys/jwt/private.key``

2020-06-17 15:24 UTC, nigelgbanks commented on scripts/islandora/generate_jwt_keys.sh
> +#!/bin/bash
Behaviour has changed since https://github.com/Islandora-Devops/isle-buildkit/pull/47

It is now an environment/configuration property rather than something that gets generated when the image is run. Though in principal its good to have a script like this to generate the properties for users, it just needs to come in as property.

2020-06-17 15:27 UTC, nigelgbanks commented on scripts/islandora/simplified_islandora_install.sh
> +/opt/scripts/islandora/generate_jwt_keys.sh
No longer needed as part of an install, could this instead be moved to the make file and included an env variables?

2020-06-17 15:28 UTC, nigelgbanks commented on docker-compose.yml
> +  etcd:
Should we remove `etcd` from the `docker-compose.yml` file, and instead have users edit an environment file? It will be easier for local development. Also for things like having the makefile generate the public/private keys.

2020-06-17 15:35 UTC, nigelgbanks commented on config/drupal/settings.php.local
> +$databases['default']['default'] = array (
Seems to be missing the `fedora` configuration for `flysystem`.

I'm not getting any files persisted into Fedora on the local configuration.

2020-06-17 15:39 UTC, noahwsmith commented
^ good comments @nigelgbanks . How does this relate to https://github.com/Islandora-Devops/isle-buildkit/pull/52/files - if you're retooling the Drupal install process, maybe we should utilize your new work to solve these issues which largely involve getting scripts to do the work of the sandbox install/setup scripts?

2020-06-17 15:42 UTC, nigelgbanks requested changes
I think this can pretty much go in as is, It's really good progress on the developer stories. Issues like `fedora flysystem` can be iterated on afterwards.

The only change I would say should go in before merging is the one line change to `config/drupal/key.key.islandora_rsa_key.yml`.

~Turns out I'm getting a bit confused, the  `docker-compose.local.yml` file is using `islandora/composer` as it's base not `islandora/drupal`. The JWT generation happens in the `islandora/drupal` image and doesn't apply here.~

No I was right originally, got mixed up in that the composer image is two staged and the second stage does use `islandora/drupal`

2020-06-17 15:58 UTC, nigelgbanks commented
> ^ good comments @nigelgbanks . How does this relate to https://github.com/Islandora-Devops/isle-buildkit/pull/52/files - if you're retooling the Drupal install process, maybe we should utilize your new work to solve these issues which largely involve getting scripts to do the work of the sandbox install/setup scripts?

That pull only covers a Drupal installation, I haven't cleaned up the `islandora/sandbox` image, yet. If everyone is happy with that general pattern I'll do the same for `islandora/sandbox`.

In the `islandora/sandbox` image we get some duplicated code with `simplified_islandora_install.sh` though the same pattern applies of moving logic out to callable scripts which could be shared across images and pulling in confd settings into the environment to simplify calling those scripts. 

I think maybe in isle-buildkit setting up another image islandora which has the common scripts which could be then shared by downstream images like the sandbox/composer or the custom one in isle-dc, could help simplify the customisation of downstream images.

2020-06-17 20:46 UTC, noahwsmith commented
I'd be a big fan of consolidating those initial init/setup scripts into the Drupal container, but then only executing them automatically on the sandbox image. The benefit would be that they'd be available to run manually on the Composer image if anyone wanted to replicate the sandbox's setup without being bound to a sandbox workflow.

And I defer to the sandbox scripts- they're more correct than this project's islandora_install or the _simplified one.

2020-06-17 20:46 UTC, noahwsmith commented on docker-compose.yml
> +  etcd:
I was just talking to @g7morris - he agrees and will port over the new sample.env settings from the buildkit repo. We can then kill the etcd service here.

2020-06-17 20:47 UTC, noahwsmith commented on scripts/islandora/simplified_islandora_install.sh
> +/opt/scripts/islandora/generate_jwt_keys.sh
Yes please. I defer to your other scripts.

2020-06-17 20:47 UTC, noahwsmith commented on scripts/islandora/generate_jwt_keys.sh
> +#!/bin/bash
Ok let's kill this if it isn't necessary.

2020-06-17 20:49 UTC, noahwsmith commented on config/drupal/key.key.islandora_rsa_key.yml
> +  file_location: /opt/keys/claw/private.key
fixed

2020-06-17 20:49 UTC, noahwsmith commented on docs/recipes/DEMO.md
> +  * `docker-compose pull`
I fixed this in the docs - thanks

2020-06-18 09:12 UTC, nigelgbanks approved these changes

2020-06-18 13:28 UTC, dannylamb approved these changes
I managed to run through the Demo instructions.  The `make install_islandora` command needs to be removed from the docs since it runs automatically.  I tried throwing in a `dsm` in the codebase and that isn't coming through, but I think I need to do the "local" build instead of "demo".

Nonetheless, it brought up a site.  I'm :+1: to pulling this in sooner rather than later.  It's a big pull and we still need to iterate to pull out slivers of the setup scripts into the drupal container. So lets do it. :rocket:

2020-06-18 13:37 UTC, merged

2020-06-18 15:35 UTC, noahwsmith commented
Terrific- thank you!